major/urls.py
# -*- coding: utf-8 -*-
# 18-11-3 下午1:21
# AUTHOR:June
from django.conf.urls import url
from major.views import LoginView, LogoutView, IndexView, LoginRecView, SetPwdView\
    , UploadDataView, SearchView, SendView, AduLogView, AduLogpageView, BatchDeleteView, DownloadInfoView\
    , UploadRecord,AdgManageView,AduManageView,DeleteView,SearchAdminView,LoginRecSearchView\
    , AddGroupView,DelGroupView,SearchGroupView,VerifyCodeView

app_name = 'major'
urlpatterns = [
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^index$', IndexView.as_view(), name='index'),
    url(r'^loginrecs/(?P<page>\d+)$', LoginRecView.as_view(), name='loginRec'),
    url(r'^uploadData$', UploadDataView.as_view(), name='uploadData'),  # end june
    url(r'^search$', SearchView.as_view(), name='search'),
    url(r'^send$', SendView.as_view(), name='send'),
    url(r'^adulog$', AduLogView.as_view(), name='adulog'),
    url(r'^adulogpage$', AduLogpageView.as_view(), name='adulogpage'),
    url(r'^batchdelete$', BatchDeleteView.as_view(), name='batchdelete'),
    url(r'^downloadinfo$', DownloadInfoView.as_view(), name='downloadinfo'),
    url(r'^uploadrecord$', UploadRecord.as_view(), name='uploadrecord'),  # end li
    url(r'^updatepwd/(?P<page>\d+)$', SetPwdView.as_view(), name='updatepwd'),
    url(r'^delete$', DeleteView.as_view(), name='delete'),  # 删除用户
    url(r'^adumanage/(?P<page>\d+)$', AduManageView.as_view(), name='adumanage'),
    url(r'^adgmanage/(?P<page>\d+)$', AdgManageView.as_view(), name='adgmanage'),
    url(r'^delgroup$', DelGroupView.as_view(), name='delgroup'),
    url(r'^addgroup$', AddGroupView.as_view(), name='AddGroupView'),
    url(r'^search/group$', SearchGroupView.as_view(), name='addgroup'),
    url(r'^search/admin$', SearchAdminView.as_view(), name='searchadmin'),
    url(r'^login/search/(?P<page>\d+)$', LoginRecSearchView.as_view(), name='loginrecsearch'),  # end tang
    url(r'^verifycode$', VerifyCodeView.as_view(), name='verifycode'),
]

payout/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('major.urls', namespace='major'))
]

templates/NoPermission.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
    <h1>没有权限</h1>
</body>
</html>

templates/aduRecord.html
{% extends 'base.html' %}
{% block side %}
        <div class="sidebar" data-background-color="" data-active-color="danger">
        <div class="logo">
            <a href="/index" class="simple-text">
                管 理 平 台
            </a>
        </div>
        <div class="logo logo-mini"><a href="#" class="simple-text">C</a></div>
        <div class="sidebar-wrapper">
            <ul class="nav first-nav">
                <li>
                    <a href="/index">
                        <i class="ti-panel"></i>
                        <p>我的首页</p>
                    </a>
                </li>
                <li>
                    <a data-toggle="collapse" href="#charts" class="collapsed" aria-expanded="true">
                        <i class="ti-bar-chart-alt"></i>
                        <p>管理员管理
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse in" id="charts" role="navigation" aria-expanded="true">
                        <ul class="nav">
                            <li ><a href="/updatepwd/1">修改管理员</a></li>
                            <li><a href="/adumanage/1">增加管理员</a></li>
                            <li><a href="/loginrecs/1">登录记录</a></li>
                            <li><a href="/adgmanage/1">权限组管理</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#ui-elements" class="collapsed" aria-expanded="false">
                        <i class="ti-package"></i>
                        <p>信息查询
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="ui-elements" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/search">查询信息</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#forms" class="collapsed" aria-expanded="false">
                        <i class="ti-clipboard"></i>
                        <p>上传数据包
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="forms" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/uploadData">上传数据</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#tables" class="collapsed" aria-expanded="false">
                        <i class="ti-view-list-alt"></i>
                        <p>信息管理
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="tables" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/adulog">管理员记录</a></li>
                            <li><a href="/batchdelete">批量删除</a></li>
                            <li><a href="/downloadinfo">下载信息</a></li>
                            <li><a href="/uploadrecord">上传记录</a></li>
                        </ul>
                    </div>
                </li>

            </ul>
        </div>
    </div>
{% endblock side %}

{% block body %}
        <div class="content">
            <div class="container-fluid">
                <div id="aduRecord" class="row wrapper wrapper-content">

                    <div class="row warnlip">未查找到相应结果！</div>
                    <div class="row tablelist">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="panel-title">
                                        <em class="list_icon"></em>
                                        管理员登录记录
                                    </div>
                                </div>

                                <div class="panel-body">
                                    <form class="form-search" action="/login/search/1" method="get">
                                        <div class="am-col col-lg-4" style="float: right">
                                                <div class="am-input-group">
                                                    <span class="am-input-group-btn" id="search-btn">
                                                        <button class="am-btn am-btn-default" type="submit">搜 索</button>
                                                        <i class="search-icon"></i>
                                                    </span>
                                                    <input type="text" class="am-form-field" name="search">
                                                </div>
                                        </div>
                                    </form>
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>管理员</th>
                                                    <th>操作时间</th>
                                                    <th>操作类型</th>
                                                    <th>IP地址</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                {% for rec in login_rec %}
                                                <tr>
                                                    <td>{{ rec.id }}</td>
                                                    <td>{{ rec.name }}</td>
                                                    <td>{{ rec.create_time }}</td>
                                                    {% if rec.state %}<td>登陆成功</td>{% else %}<td class="deliveried">登陆失败</td>{% endif %}
                                                    <td>{{ rec.ip }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="span12" id="dPager">
                                        <div class="pager">
                                           {% if login_rec.has_previous %}
<li><a class="prev" href="{% url 'major:loginRec' login_rec.previous_page_number %}">上一页</a></li>
{% endif %}

{% for pindex in pages %}
{% if pindex == login_rec.number %}
<li><span class="current">{{ pindex }}</span></li>
{% else %}
<li><a href="{% url 'major:loginRec' pindex %}">{{ pindex }}</a></li>
{% endif %}

{% endfor %}
{% if login_rec.has_next %}
<li><a class="next" href="{% url 'major:loginRec' login_rec.next_page_number %}">下一页</a></li>
{% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock body %}

templates/aduRecordSearch.html
{% extends 'base.html' %}
{% block side %}
<div class="sidebar" data-background-color="" data-active-color="danger">
        <div class="logo">
            <a href="/index" class="simple-text">
                管 理 平 台
            </a>
        </div>
        <div class="logo logo-mini"><a href="#" class="simple-text">C</a></div>
        <div class="sidebar-wrapper">
            <ul class="nav first-nav">
                <li>
                    <a href="/index">
                        <i class="ti-panel"></i>
                        <p>我的首页</p>
                    </a>
                </li>
                <li>
                    <a data-toggle="collapse" href="#charts" class="collapsed" aria-expanded="true">
                        <i class="ti-bar-chart-alt"></i>
                        <p>管理员管理
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse in" id="charts" role="navigation" aria-expanded="true">
                        <ul class="nav">
                            <li ><a href="/updatepwd/1">修改管理员</a></li>
                            <li><a href="/adumanage/1">增加管理员</a></li>
                            <li><a href="/loginrecs/1">登录记录</a></li>
                            <li><a href="/adgmanage/1">权限组管理</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#ui-elements" class="collapsed" aria-expanded="false">
                        <i class="ti-package"></i>
                        <p>信息查询
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="ui-elements" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/search">查询信息</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#forms" class="collapsed" aria-expanded="false">
                        <i class="ti-clipboard"></i>
                        <p>上传数据包
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="forms" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/uploadData">上传数据</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#tables" class="collapsed" aria-expanded="false">
                        <i class="ti-view-list-alt"></i>
                        <p>信息管理
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="tables" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/adulog">管理员记录</a></li>
                            <li><a href="/batchdelete">批量删除</a></li>
                            <li><a href="/downloadinfo">下载信息</a></li>
                            <li><a href="/uploadrecord">上传记录</a></li>
                        </ul>
                    </div>
                </li>

            </ul>
        </div>
    </div>
{% endblock side %}
{% block body %}
        <div class="content">
            <div class="container-fluid">
                <div id="aduRecord" class="row wrapper wrapper-content">

                    <div class="row warnlip">未查找到相应结果！</div>
                    <div class="row tablelist">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="panel-title">
                                        <em class="list_icon"></em>
                                        管理员登录记录
                                    </div>
                                </div>

                                <div class="panel-body">
                                    <form class="form-search" action="/login/search/1" method="get">
                                        <div class="am-col col-lg-4" style="float: right">
                                                <div class="am-input-group">
                                                    <span class="am-input-group-btn" id="search-btn">
                                                        <button class="am-btn am-btn-default" type="submit">搜 索</button>
                                                        <i class="search-icon"></i>
                                                    </span>
                                                    <input type="text" class="am-form-field" name="search">
                                                </div>
                                        </div>
                                    </form>
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>管理员</th>
                                                    <th>操作时间</th>
                                                    <th>操作类型</th>
                                                    <th>IP地址</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                {% for rec in login_rec %}
                                                <tr>
                                                    <td>{{ rec.id }}</td>
                                                    <td>{{ rec.name }}</td>
                                                    <td>{{ rec.create_time }}</td>
                                                    <td>{% if rec.state %}登陆成功{% else %}登陆失败{% endif %}</td>
                                                    <td>{{ rec.ip }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div style="text-align:center !important; color:red;">{{msg}}</div>
                                    <div class="span12" id="dPager">
                                        <div class="pager" style="">

                                           {% if login_rec.has_previous %}
<li><a class="prev" href="{% url 'major:loginrecsearch' login_rec.previous_page_number %}?search={{ search_word }}"  >上一页</a></li>
{% endif %}

{% for pindex in pages %}
{% if pindex == login_rec.number %}
<li><span class="current">{{ pindex }}</span></li>
{% else %}

<li><a href="{% url 'major:loginrecsearch' pindex %}?search={{ search_word }}">{{ pindex }}</a></li>
{% endif %}

{% endfor %}
{% if login_rec.has_next %}
<li><a class="next" href="{% url 'major:loginrecsearch' login_rec.next_page_number %}?search={{ search_word }}">下一页</a></li>
{% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock body %}


templates/adulog.html
{% extends 'base.html' %}
{% block side %}
        <div class="sidebar" data-background-color="" data-active-color="danger">
        <div class="logo">
            <a href="/index" class="simple-text">
                管 理 平 台
            </a>
        </div>
        <div class="logo logo-mini"><a href="#" class="simple-text">C</a></div>
        <div class="sidebar-wrapper">
            <ul class="nav first-nav">
                <li>
                    <a href="/index">
                        <i class="ti-panel"></i>
                        <p>我的首页</p>
                    </a>
                </li>
                <li>
                    <a data-toggle="collapse" href="#charts" class="collapsed" aria-expanded="false">
                        <i class="ti-bar-chart-alt"></i>
                        <p>管理员管理
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="charts" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li ><a href="/updatepwd/1">修改管理员</a></li>
                            <li><a href="/adumanage/1">增加管理员</a></li>
                            <li><a href="/loginrecs/1">登录记录</a></li>
                            <li><a href="/adgmanage/1">权限组管理</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#ui-elements" class="collapsed" aria-expanded="false">
                        <i class="ti-package"></i>
                        <p>信息查询
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="ui-elements" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/search">查询信息</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#forms" class="collapsed" aria-expanded="false">
                        <i class="ti-clipboard"></i>
                        <p>上传数据包
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="forms" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li><a href="/uploadData">上传数据</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a data-toggle="collapse" href="#tables" class="collapsed" aria-expanded="true">
                        <i class="ti-view-list-alt"></i>
                        <p>信息管理
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse in" id="tables" role="navigation" aria-expanded="false" style="height: 0px;">
                        <ul class="nav">
                            <li class="active"><a href="/adulog">管理员记录</a></li>
                            <li><a href="/batchdelete">批量删除</a></li>
                            <li><a href="/downloadinfo">下载信息</a></li>
                            <li><a href="/uploadrecord">上传记录</a></li>
                        </ul>
                    </div>
                </li>

            </ul>
        </div>
    </div>
{% endblock side %}
{% block body %}
    <div class="content">
            <div class="container-fluid">
                <div id="adulog" class="row wrapper wrapper-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="panel-title">
                                        <em class="updatepw_icon"></em>
                                        管理员记录
                                    </div>
                                </div>

                                <form action="./adulog" method="post">
                                {% csrf_token %}
                                <div class="panel-body">
                                    <div class="content-box form-ajax form-horizontal">
                                        <div class="form-group">
                                            <label class="col-md-2 control-label">
                                                信息开始时间：
                                            </label>
                                            <div class="col-md-9 c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                                <input type="text" name="startTime" id="startTime" class="form-control" maxlength="20" required="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2 control-label">
                                                信息结束时间：
                                            </label>
                                            <div class="col-md-9 c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                                <input type="text" name="endTime" id="endTime" class="form-control" maxlength="20" required="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2 control-label">
                                               管理员：
                                            </label>
                                            <div class="col-md-9">
                                                <select id="BankCode" name="BankCode" class="form-control">
                                                    <option value="0">全部</option>
                                                    {% for adu in adus %}
                                                    <option value="{{ adu.username }}">{{ adu.username }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-offset-5 col-md-4">
                                                <button type="submit" class="btn subBtnstl" id="btnUpdateLoginPWD"> &nbsp;查 &nbsp; &nbsp;询&nbsp;</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </form>

                            </div>
                        </div>
                    </div>

                    {% if result %}

                        {% if records %}
                        <div class="row tablelist">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="panel-title">
                                        <em class="list_icon"></em>
                                        记录列表
                                    </div>
                                </div>

                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>上传时间</th>
                                                    <th>姓名</th>
                                                    <th>派送彩金</th>
                                                    <th>QQ</th>
                                                    <th>电话号码</th>
                                                    <th>电子邮箱</th>
                                                    <th>派送时间</th>
                                                    <th>操作人</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                            {% for record in records %}
                                                <tr>
                                                    <td>{{ record.create_time }}</td>
                                                    <td>{{ record.name }}</td>
                                                    <td>{{ record.money }}</td>
                                                    <td>{{ record.qq }}</td>
                                                    <td>{{ record.tel }}</td>
                                                    <td>{{ record.email }}</td>
                                                    <td>{{ record.send_time }}</td>
                                                    <td>{{ record.operator }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="span12" id="dPager">
                                        <div class="pager">
                                            <ul>
                                                <li><a class="first" href="./adulogpage?startTime={{ startTime }}&endTime={{ endTime }}&BankCode={{ BankCode }}&page=1">首页</a></li>
                                                {% if records.has_previous %}
                                                <li><a class="prev" href="./adulogpage?startTime={{ startTime }}&endTime={{ endTime }}&BankCode={{ BankCode }}&page={{ records.previous_page_number }}">上一页</a></li>
                                                {% endif %}
                                                {% for pindex in pages %}
                                                    <li><a href="./adulogpage?startTime={{ startTime }}&endTime={{ endTime }}&BankCode={{ BankCode }}&page={{ pindex }}" {% if pindex == skus_page.number %}class="current"{% endif %}>{{ pindex }}</a></li>
                                                {% endfor %}
                                                {% if records.has_next %}
                                                <li><a class="next" href="./adulogpage?startTime={{ startTime }}&endTime={{ endTime }}&BankCode={{ BankCode }}&page={{ records.next_page_number }}">下一页</a></li>
                                                {% endif %}
                                                <li><span class="rows">共{{ count }}条记录</span></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                        {% else %}
                            <h3 style="color: red">未查找到相应结果！</h3>
                        {% endif %}
                    {% endif %}

                </div>
            </div>
        </div>
{% endblock body %}
